# Generated by Django 5.2.7 on 2025-10-11 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors_movie_genre_movie_release_data_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0'), django.core.validators.MaxValueValidator(5, 'Avaliação nao pode ser superior a 5')]),
            preserve_default=False,
        ),
    ]
